import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reg Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {children}


        
{/* Top Left */}
{/* Top Left */}
{/* Top Left */}
{/* <div className="circuit-line horizontal" style={{ top: "10px", left: "10px", width: "110px" }}></div>
<div className="circuit-line vertical" style={{ top: "10px", left: "10px", height: "60px" }}></div>

<div className="circuit-line horizontal" style={{ top: "80px", left: "28px", width: "15px", transform: "rotate(50deg)" }}></div>
<div className="circuit-line horizontal" style={{ top: "50px", left: "50px", width: "25px", transform: "rotate(50deg)" }}></div>

<div className="circuit-line horizontal" style={{ top: "100px", left: "14px", width: "20px", transform: "rotate(130deg)" }}></div>
<div className="circuit-line horizontal" style={{ top: "105px", left: "28px", width: "20px", transform: "rotate(50deg)" }}></div>

<div className="circuit-line vertical" style={{ top: "108px", left: "17px", height: "100px" }}></div>
<div className="circuit-line vertical" style={{ top: "113px", left: "43px", height: "60px" }}></div>




<div className="circuit-line horizontal" style={{ top: "40px", left: "30px", width: "60px" }}></div>
<div className="circuit-line vertical" style={{ top: "10px", left: "30px", height: "120px" }}></div>



<div className="circuit-line horizontal" style={{ top: "60px", left: "60px", width: "40px" }}></div>
<div className="circuit-line vertical" style={{ top: "60px", left: "100px", height: "40px",}}></div>

<div className="node" style={{ top: "10px", left: "8px" }}></div>
<div className="node" style={{ top: "60px", left: "58px" }}></div>
<div className="node" style={{ top: "100px", left: "98px" }}></div>
<div className="node" style={{ top: "208px", left: "14px" }}></div>
<div className="node" style={{ top: "170px", left: "40px" }}></div> */}



{/* Top Right */}
{/* <div className="circuit-line horizontal" style={{ top: "10px", right: "10px", width: "60px" }}></div>
<div className="circuit-line vertical" style={{ top: "10px", right: "10px", height: "130px" }}></div>

<div className="circuit-line horizontal" style={{ top: "18px", right: "30px", width: "20px",  transform: "rotate(130deg)" }}></div>
<div className="circuit-line horizontal" style={{ top: "36px", right: "8px", width: "20px",  transform: "rotate(130deg)" }}></div>

<div className="circuit-line horizontal" style={{ top: "26px", right: "46px", width: "60px", }}></div>

<div className="circuit-line horizontal" style={{ top: "50px", right: "58px", width: "14px",  transform: "rotate(130deg)" }}></div>
<div className="circuit-line vertical" style={{ top: "56px", right: "68px", height: "50px" }}></div>



<div className="circuit-line vertical" style={{ top: "28px", right: "60px", height: "40px" }}></div>

<div className="circuit-line horizontal" style={{ top: "50px", right: "8px", width: "20px",  transform: "rotate(130deg)" }}></div>
<div className="circuit-line vertical" style={{ top: "58px", right: "23px", height: "40px" }}></div>

<div className="circuit-line horizontal" style={{ top: "64px", right: "46px", width: "16px",  transform: "rotate(40deg)" }}></div>
<div className="circuit-line vertical" style={{ top: "70px", right: "47px", height: "40px" }}></div>




<div className="node" style={{ top: "10px", right: "8px" }}></div>
<div className="node" style={{ top: "8px", right: "70px" }}></div>
<div className="node" style={{ top: "140px", right: "7px" }}></div> */}

{/* Bottom Left */}
{/* <div className="circuit-line horizontal" style={{ bottom: "10px", left: "10px", width: "60px" }}></div>
<div className="circuit-line vertical" style={{ bottom: "10px", left: "10px", height: "100px" }}></div>

<div className="circuit-line vertical" style={{ bottom: "60px", left: "17px", height: "20px", transform: "rotate(40deg)"  }}></div>



<div className="circuit-line vertical" style={{ bottom: "76px", left: "23px", height: "100px" }}></div>



<div className="circuit-line horizontal" style={{ bottom: "24px", left: "24px", width: "20px"}}></div>

<div className="circuit-line vertical" style={{ bottom: "30px", left: "28px", height: "20px" }}></div>

<div className="circuit-line vertical" style={{ bottom: "60px", left: "100px", height: "40px" }}></div>

<div className="circuit-line vertical" style={{ bottom: "6px", left: "39px", height: "70px", transform: "rotate(46deg)" }}></div>



<div className="node" style={{ bottom: "10px", left: "8px" }}></div>
<div className="node" style={{ bottom: "60px", left: "58px" }}></div>
<div className="node" style={{ bottom: "100px", left: "98px" }}></div>
<div className="node" style={{ bottom: "170px", left: "20px" }}></div> */}


{/* Bottom Right */}
{/* <div className="circuit-line horizontal" style={{ bottom: "10px", right: "10px", width: "60px" }}></div>
<div className="circuit-line vertical" style={{ bottom: "10px", right: "10px", height: "60px" }}></div>
<div className="circuit-line horizontal" style={{ bottom: "60px", right: "60px", width: "40px" }}></div>
<div className="circuit-line vertical" style={{ bottom: "60px", right: "100px", height: "40px" }}></div>
<div className="node" style={{ bottom: "10px", right: "8px" }}></div>
<div className="node" style={{ bottom: "60px", right: "58px" }}></div>
<div className="node" style={{ bottom: "100px", right: "98px" }}></div> */}





     
      </body>
    </html>
  );
}
